### ISSUE TITLE
is there any way to not to use bootstrap 

### ISSUE THREAD

**Issue by mominsamir** [ethanhann/eeh-navigation#10]
I am using material design for my project, I don't want to use bootstrap, is it possible ? if yes what how do to do it.

**Comment by ethanhann** [comment]
I am glad you asked this question, because that is one of my goals for version 4. I did some work to make the code more modular which will allow additional non-Bootstrap directives to be built on top of the underlying menu service. 

I am still deciding which front-end frameworks to build directives for. Which material design framework are you using? [Angular Material](https://material.angularjs.org/latest/#/)?

**Comment by mominsamir** [comment]
Thanks for your reply, I am using angular material for my web app.

**Comment by ethanhann** [comment]
I'll experiment with adding directives for Angular Material. I'll let you know how it goes.

**Comment by mominsamir** [comment]
thanks waiting to use it.

**Comment by mominsamir** [comment]
thanks using MetisMenu integration

**Comment by ethanhann** [comment]
I played around with Angular Material a little bit. I plan to add support for that too.

**Comment by grimurd** [comment]
@ethanhann any news on this?

**Comment by ethanhann** [comment]
@Sk1Zy It is possible to build a non-Bootstrap menu as of version 4. I never built an Angular Material directive because I haven't had the time.
