### ISSUE TITLE
Why are multi-level menu items "active" when they haven't been selected yet?

### ISSUE THREAD

**Issue by Furburger** [ethanhann/eeh-navigation#25]
Hi

If you look at your Bootstrap Navbar example, the Multi-Level menu-items in the SideBar are "active" when you first load the page.

If you then click on "Blank", even more Multi-Level menu-items suddenly become "active.

Why is this?

See these screen shots.

![example1](https://cloud.githubusercontent.com/assets/5500245/11391114/b9405cfe-9358-11e5-81b5-8609e170fb30.png)

![example2](https://cloud.githubusercontent.com/assets/5500245/11391142/de1dbca6-9358-11e5-9261-98a614837132.png)

**Comment by ethanhann** [comment]
Yeah, the demo could be better. They are active because they are all pointing to the same ui-router state which is active. The purpose of that feature is to be able to tell when a deeply nested menu item is active.

**Comment by ethanhann** [comment]
The demo examples, especially the BS navbar and sidebar, kind of grew organically as I added features. I've been thinking about redoing the demos in codepen to make them clearer and more helpful.

**Comment by warapitiya** [comment]
+1

Having the same problem. 2nd level sidebar menus are getting applied by the **active** css class when select one button.

I don't this will be a feature. if it is please add it to a configuration property and enable both.

**Comment by ethanhann** [comment]
@warapitiya That is an intentional feature so that you can find deeply nested active children in collapsed menus. If you do not desire that behavior feel free to submit a PR making it configurable or you can override the default style of the active parent menu items to make them look however you want - see: https://github.com/ethanhann/eeh-navigation/issues/46
