### ISSUE TITLE
Support to markup in menu item text?

### ISSUE THREAD

**Issue by bharathitman** [ethanhann/eeh-navigation#49]
I am using your plugin to great effect in one of my projects. However, I have come across a situation where in I need to show a notification style counter right next to the menu name. Something like this
![image](https://cloud.githubusercontent.com/assets/994536/14614846/958d7a82-05c0-11e6-877a-00be713ab11c.png)

 Currently the API includes text, icon and href. Inclusion of markup isn't possible. Am I missing something here?

**Comment by ethanhann** [comment]
Currently I don't think that is possible. Support for that would have to be added by using ng-bind-html to attach the HTML to the menu item. There should probably be a separate menu item property called "markup" that gets passed into ng-bind-html. I added this feature to the 5.0.0-beta1 milestone because it sounds useful.

I haven't had a chance to work on this project over the last few months which is a shame because 5.0.0 is pretty much done. All my obligations should be winding down in the next few weeks. Hopefully around mid May I will have the stable 5.0.0 release finished.

**Comment by RipleWare** [comment]
Just wondering if this is still in progress?  I would like to utilise this feature also.

**Comment by ethanhann** [comment]
It is now possible to add arbitrary HTML.

Using ngBindHtml as a function...
```js
.menuItem('nav.example', {
    text: 'Example',
    href: 'example.com',
    ngBindHtml: function () {
        return '<span class="label label-default">hello</span>';
    }
})
```

Using ngBindHtml as a string...
```js
.menuItem('nav.example', {
    text: 'Example',
    href: 'example.com',
    ngBindHtml: '<span class="label label-default">hello</span>'
})
```

Using ngInclude to include a template...
```js
.menuItem('nav.example', {
    text: 'Example',
    ngInclude: 'path/to/template.html'
})
```
